import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const lockPath = path.join(scriptDirectory, "package-lock.json");
const outputPath = path.resolve(
  scriptDirectory,
  "../Sources/CodeMirror/web.bundle/THIRD-PARTY-NOTICES.md"
);
const lockText = await readFile(lockPath, "utf8");
const lockfile = JSON.parse(lockText);
const packages = Object.entries(lockfile.packages ?? {})
  .filter(([packagePath]) => packagePath.startsWith("node_modules/"))
  .map(([packagePath, metadata]) => ({
    name: packagePath.slice("node_modules/".length),
    version: metadata.version ?? "unknown",
    license: metadata.license ?? "UNKNOWN",
    resolved: metadata.resolved ?? "not listed",
    integrity: metadata.integrity ?? "not listed"
  }))
  .sort((left, right) => left.name.localeCompare(right.name));
const licenseCounts = new Map();
for (const metadata of packages) {
  licenseCounts.set(metadata.license, (licenseCounts.get(metadata.license) ?? 0) + 1);
}
const lockHash = createHash("sha256").update(lockText).digest("hex");
const escapeTableValue = value => String(value).replaceAll("|", "\\|");
const inventory = [...licenseCounts.entries()]
  .sort(([left], [right]) => left.localeCompare(right))
  .map(([license, count]) => `${license} (${count})`)
  .join(", ");
const lines = [
  "# Third-Party Notices",
  "",
  "This notice is generated by `npm run generate-notices` from the committed `codemirrorjs/package-lock.json`.",
  "The inventory includes every locked transitive package, including optional platform packages, with its locked registry URL and integrity digest.",
  "",
  `Package-lock SHA-256: ${lockHash}`,
  `Locked package count: ${packages.length}`,
  `License inventory: ${inventory}`,
  "",
  "| Package | Version | License | Locked source | Integrity |",
  "| --- | --- | --- | --- | --- |",
  ...packages.map(metadata =>
    `| ${escapeTableValue(metadata.name)} | ${escapeTableValue(metadata.version)} | ${escapeTableValue(metadata.license)} | ${escapeTableValue(metadata.resolved)} | ${escapeTableValue(metadata.integrity)} |`
  ),
  "",
  "The package license identifiers and source digests above are taken from npm lock metadata. Re-run the generator after any dependency change; a changed lockfile hash or inventory is an intentional review signal."
];
await writeFile(outputPath, `${lines.join("\n")}\n`, "utf8");
